/** @vitest-environment jsdom */
import '@testing-library/jest-dom/vitest'
import { cleanup, fireEvent, render, screen } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
const mocks = vi.hoisted(() => ({ query: '' }))
vi.mock('next/navigation', () => ({ useSearchParams: () => new URLSearchParams(mocks.query) }))
vi.mock('@/components/PronounceButton', () => ({ default: () => <button>发音</button> }))
vi.mock('@/components/SentenceTTSButton', () => ({ default: () => <button>朗读句子</button> }))
vi.mock('@/components/WordBookmarkButton', () => ({ WordBookmarkButton: () => <button>收藏单词</button> }))
vi.mock('@/components/SelectionSearch', () => ({ default: ({ children }: { children: React.ReactNode }) => children }))
import LearnPage from './page'

const item = { id: null, meaningId: 'meaning-1', wordId: 'word-1', word: 'agent', bookmarked: false, pos: 'noun', definition: 'a representative', definitionCn: '代理人', sentence: 'The secret agent was caught.', sentenceCn: '秘密特工被抓住了。' }
const reply = (data: unknown, status = 200) => new Response(JSON.stringify(data), { status })
afterEach(() => { cleanup(); vi.unstubAllGlobals(); mocks.query = '' })
describe('direct word learning', () => {
  it('retains the word and corrected rating if immediate forgotten submission fails', async () => {
    const fetchMock = vi.fn().mockResolvedValueOnce(reply(item)).mockResolvedValueOnce(reply({}, 500))
    vi.stubGlobal('fetch', fetchMock)
    render(<LearnPage />)
    await screen.findByRole('link', { name: 'agent' })
    fireEvent.click(screen.getByRole('button', { name: '记得' }))
    const definition = screen.getByText('代理人').closest('.learn-definition-reveal')
    expect(definition).not.toBeNull()
    expect(screen.queryByRole('button', { name: '记得' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: '模糊' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '忘记' }))
    await screen.findByRole('alert')
    expect(screen.getByText('代理人').closest('.learn-definition-reveal')).toBe(definition)
    expect(screen.queryByRole('button', { name: '忘记' })).not.toBeInTheDocument()
    expect(fetchMock).toHaveBeenCalledTimes(2)
  })
  it('centers the word independently of the bookmark and places sentence audio before a wrapping sentence', async () => {
    vi.stubGlobal('fetch', vi.fn().mockResolvedValue(reply(item)))
    render(<LearnPage />)
    const word = await screen.findByRole('heading', { name: 'agent' })
    expect(word).toHaveClass('text-center')
    expect(word.parentElement?.parentElement).toHaveClass('justify-center', 'relative')
    expect(screen.getByRole('button', { name: '收藏单词' }).parentElement).toHaveClass('absolute', 'right-0')
    const audio = screen.getByRole('button', { name: '朗读句子' })
    expect(audio.parentElement).toHaveClass('shrink-0', 'h-8')
    expect(audio.parentElement?.parentElement).toHaveClass('flex', 'items-start')
    expect(audio.parentElement?.nextElementSibling).toHaveTextContent('The secret agent was caught.')
    expect(audio.parentElement?.nextElementSibling).toHaveClass('min-w-0', 'flex-1', 'break-words')
  })
  it('gives rating buttons visible hover feedback and a distinct selected state', async () => {
    vi.stubGlobal('fetch', vi.fn().mockResolvedValue(reply(item)))
    render(<LearnPage />)
    await screen.findByRole('link', { name: 'agent' })
    for (const label of ['记得', '模糊', '忘记']) {
      expect(screen.getByRole('button', { name: label })).toHaveClass('shadow-sm', 'enabled:hover:bg-stone-200', 'enabled:hover:text-stone-900', 'dark:enabled:hover:bg-stone-700')
    }
    fireEvent.click(screen.getByRole('button', { name: '记得' }))
    expect(screen.queryByRole('button', { name: '记得' })).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: '忘记' })).toHaveClass('shadow-sm', 'enabled:hover:bg-stone-200')
  })
  it('keeps loading within the selected group and resets state when the group changes', async () => {
    mocks.query = 'groupId=group%2F2'
    const fetchMock = vi.fn().mockResolvedValueOnce(reply({ done: true })).mockResolvedValueOnce(reply(item)).mockResolvedValueOnce(reply({ newMastery: 63 })).mockResolvedValueOnce(reply({ ...item, word: 'advance', meaningId: 'meaning-2' }))
    vi.stubGlobal('fetch', fetchMock)
    const { rerender } = render(<LearnPage />)
    await screen.findByRole('heading', { name: '暂时没有未背的单词' })
    expect(fetchMock).toHaveBeenNthCalledWith(1, '/api/kaoyan/learn?groupId=group%2F2', { cache: 'no-store' })
    mocks.query = 'groupId=group-3'
    rerender(<LearnPage />)
    await screen.findByRole('link', { name: 'agent' })
    expect(fetchMock).toHaveBeenNthCalledWith(2, '/api/kaoyan/learn?groupId=group-3', { cache: 'no-store' })
    fireEvent.click(screen.getByRole('button', { name: '记得' }))
    fireEvent.click(screen.getByRole('button', { name: '继续' }))
    await screen.findByRole('link', { name: 'advance' })
    expect(fetchMock).toHaveBeenNthCalledWith(4, '/api/kaoyan/learn?groupId=group-3', { cache: 'no-store' })
  })
  it('loads the next unread word without choosing a group, then saves the selected rating before advancing', async () => {
    const fetchMock = vi.fn().mockResolvedValueOnce(reply(item)).mockResolvedValueOnce(reply({ newMastery: 63 })).mockResolvedValueOnce(reply({ ...item, meaningId: 'meaning-2', wordId: 'word-2', word: 'advance' }))
    vi.stubGlobal('fetch', fetchMock)
    render(<LearnPage />)
    expect(await screen.findByRole('link', { name: 'agent' })).toHaveAttribute('href', '/word/word-1')
    expect(fetchMock).toHaveBeenCalledWith('/api/kaoyan/learn', { cache: 'no-store' })
    expect(screen.queryByText('代理人')).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '记得' }))
    expect(screen.getByText('代理人')).toBeInTheDocument()
    expect(fetchMock).toHaveBeenCalledTimes(1)
    fireEvent.click(screen.getByRole('button', { name: '继续' }))
    expect(await screen.findByRole('link', { name: 'advance' })).toBeInTheDocument()
    expect(fetchMock).toHaveBeenNthCalledWith(2, '/api/kaoyan/learn', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ meaningId: 'meaning-1', grade: 4 }) })
  })
  it('rates the exact existing progress record rather than initializing another meaning', async () => {
    const fetchMock = vi.fn().mockResolvedValueOnce(reply({ ...item, id: 'pending-1' })).mockResolvedValueOnce(reply({ newMastery: 58 })).mockResolvedValueOnce(reply({ done: true }))
    vi.stubGlobal('fetch', fetchMock)
    render(<LearnPage />)
    await screen.findByRole('link', { name: 'agent' })
    fireEvent.click(screen.getByRole('button', { name: '模糊' }))
    fireEvent.click(screen.getByRole('button', { name: '继续' }))
    await screen.findByRole('heading', { name: '暂时没有未背的单词' })
    expect(fetchMock).toHaveBeenNthCalledWith(2, '/api/kaoyan/learn', expect.objectContaining({ body: JSON.stringify({ userWordMeaningId: 'pending-1', grade: 2 }) }))
  })
  it('keeps the same word and selected rating when saving fails', async () => {
    const fetchMock = vi.fn().mockResolvedValueOnce(reply(item)).mockResolvedValueOnce(reply({ error: 'failed' }, 500))
    vi.stubGlobal('fetch', fetchMock)
    render(<LearnPage />)
    await screen.findByRole('link', { name: 'agent' })
    fireEvent.click(screen.getByRole('button', { name: '忘记' }))
    fireEvent.click(screen.getByRole('button', { name: '继续' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('进度未能保存')
    expect(screen.getByRole('link', { name: 'agent' })).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: '忘记' })).not.toBeInTheDocument()
    expect(screen.getByText('代理人')).toBeInTheDocument()
    expect(fetchMock).toHaveBeenCalledTimes(2)
  })
  it('shows an explicit empty state instead of a blank page', async () => {
    vi.stubGlobal('fetch', vi.fn().mockResolvedValue(reply({ done: true })))
    render(<LearnPage />)
    expect(await screen.findByRole('heading', { name: '暂时没有未背的单词' })).toBeInTheDocument()
  })
  it('offers a retry after loading fails rather than claiming learning is complete', async () => {
    vi.stubGlobal('fetch', vi.fn().mockResolvedValueOnce(reply({}, 500)).mockResolvedValueOnce(reply(item)))
    render(<LearnPage />)
    expect(await screen.findByRole('alert')).toHaveTextContent('单词加载失败')
    fireEvent.click(screen.getByRole('button', { name: '重试' }))
    expect(await screen.findByRole('link', { name: 'agent' })).toBeInTheDocument()
  })
})

describe('List position indicator', () => {
  it('shows the current position and updates after saving the word', async () => {
    const fetchMock = vi.fn()
      .mockResolvedValueOnce(reply({ ...item, listProgress: { position: 5, total: 30 } }))
      .mockResolvedValueOnce(reply({ newMastery: 63 }))
      .mockResolvedValueOnce(reply({ ...item, word: 'advance', listProgress: { position: 6, total: 30 } }))
    vi.stubGlobal('fetch', fetchMock)
    render(<LearnPage />)
    expect(await screen.findByText('5/30')).toBeInTheDocument()
    expect(screen.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '5')
    expect(screen.getByRole('progressbar')).toHaveAttribute('aria-valuemax', '30')
    fireEvent.click(screen.getByRole('button', { name: '记得' }))
    expect(screen.getByText('5/30')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '继续' }))
    expect(await screen.findByText('6/30')).toBeInTheDocument()
    expect(screen.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '6')
  })
})

describe('correcting remembered words', () => {
  it('saves grade zero after pressing the correction button and restores ratings for the next word', async () => {
    const fetchMock = vi.fn().mockResolvedValueOnce(reply(item))
      .mockResolvedValueOnce(reply({ newMastery: 0 }))
      .mockResolvedValueOnce(reply({ ...item, word: 'advance' }))
    vi.stubGlobal('fetch', fetchMock)
    render(<LearnPage />)
    fireEvent.click(await screen.findByRole('button', { name: '记得' }))
    const save = screen.getByRole('button', { name: '继续' })
    const forgotten = screen.getByRole('button', { name: '忘记' })
    expect(save.nextElementSibling).toBe(forgotten)
    fireEvent.click(forgotten)
    await screen.findByRole('link', { name: 'advance' })
    expect(fetchMock).toHaveBeenNthCalledWith(2, '/api/kaoyan/learn', expect.objectContaining({
      body: JSON.stringify({ meaningId: 'meaning-1', grade: 0 }),
    }))
    expect(screen.getByRole('button', { name: '记得' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: '模糊' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: '忘记' })).toBeInTheDocument()
  })
})

describe('word loading without flashing messages', () => {
  it('keeps saved content during the next request and retries GET without submitting twice', async () => {
    let finish: (value: Response) => void = () => {}
    const next = new Promise<Response>(resolve => { finish = resolve })
    const fetchMock = vi.fn().mockResolvedValueOnce(reply(item)).mockResolvedValueOnce(reply({ newMastery: 63 }))
      .mockReturnValueOnce(next).mockResolvedValueOnce(reply({ ...item, meaningId: 'meaning-2', word: 'advance' }))
    vi.stubGlobal('fetch', fetchMock)
    render(<LearnPage />)
    fireEvent.click(await screen.findByRole('button', { name: '记得' }))
    fireEvent.click(screen.getByRole('button', { name: '继续' }))
    await screen.findByRole('button', { name: '…' })
    expect(screen.getByRole('link', { name: 'agent' })).toBeInTheDocument()
    expect(screen.queryByText(/正在加载/)).not.toBeInTheDocument()
    finish(reply({}, 500))
    fireEvent.click(await screen.findByRole('button', { name: '重试' }))
    await screen.findByRole('link', { name: 'advance' })
    expect(fetchMock.mock.calls.filter(([, options]) => options?.method === 'POST')).toHaveLength(1)
  })
})
